### ISSUE TITLE
Extracted link is too long and does not get closed, or the sentence is truncated too early.

### ISSUE THREAD

**Issue by erolm-a** [facebookresearch/GENRE#11]
Hi everyone,

I was working on a small experiment to perform E2E entity linking on some wikipedia pages and I noticed an interesting behaviour while playing with the size of the beam. I am attaching this colab notebook, based on your HF example:  https://colab.research.google.com/drive/1vy_lFCx2B0xvhYF09916df8UEBW5UENK#scrollTo=HLzGZ1_9v1EN . I tried feeding it a relatively long paragraph (the first paragraph of the Anarchism page on Wikipedia). The behaviour is interesting: for the first few links the model behaves correctly, but when certain links are met (in particular hierarchy) the behaviour can change erratically and ending up generating a suspiciously long wiki link that most likely does not exist but is instead the content of another page. When the beam size is too short the model simply stops generating quite early despite there are way more examples to try.

About the behaviour of GENRE with the given long example I had 2 questions:

1. Why do you think in certain cases it gives up with a long list of PAD tokens? Why does it not try to complete the whole page?
2. Why does the model report text from other wikipedia pages in place of terminating the links? May this be an error in the trie? I think I need to explore the trie structure a bit more to tell if entire pages have been erroneously spilled in the tree, and if yes if we could regenerate the tree. It is interesting that in some examples the closing "]" token is absent. Does the trie enforce the generation of the ] token or is the underlying BART model trying to do that? may this be related to #9  ?

I think the function `get_end_to_end_prefix_allowed_tokens_fn_hf` has some issues in the token selection. Hopefully I'll find some time later on to properly investigate the trie and figure 

I'll also have a try with fairseq to check if the behaviour is reproducible.

**Comment by nicola-decao** [comment]
Hi 🙂  please note that we used fairseq for all experiments in the paper. The huggingface/transformers models are obtained with a conversion script. Therefore results might differ. Can you please try to do inference with fairseq and see if the problem is still there?
