### ISSUE TITLE
Evaluation on entity linking and disambiguation 

### ISSUE THREAD

**Issue by swj0419** [facebookresearch/GENRE#14]
Hi, 

Very inspiring work! Thanks for sharing the code. I am trying to do an error analysis on the entity linking results. I was wondering if you could provide a script for evaluating the released model on the entity disambiguation/linking datasets? Thank you.

**Comment by nicola-decao** [comment]
The script for evaluation on a KILT formatted dataset is here https://github.com/facebookresearch/GENRE/blob/main/scripts/evaluate_kilt_dataset.py
