### ISSUE TITLE
Question about BPE and constrained decoding

### ISSUE THREAD

**Issue by LittlePea13** [facebookresearch/GENRE#16]
I have been working with Bart, and want to use the constrained decoding approach implemented in GENRE (congrats on the work btw). However I have a question that by looking at the code (perhaps due to my lack of fairseq skills), I am not able to clarify. 

Due to the BPE tokenization of RoBERTa, and by extension Bart, the same words may be tokenized differently, ie. `["Nicola, ", "Nicola", "[ Nicola ]", " [ Nicola ],"] `are tokenized quite differently (`[[31988, 3019, 6, 1437], [31988, 3019], [10975, 14371, 27779], [646, 14371, 47720]]`). 

If we add tokens around the entities to mark them for training and perform the Entity Linking in GENRE, that would mean that when decoding, the tokens may not be the same once the "[]{}" tokens are added, ie. source and target show different tokens. Is there something I am missing to deal with this when using the constrained decoding which continues generation from the source tokens and may differ from what is seen at training in the target text?

Thanks!

**Comment by nicola-decao** [comment]
Hi, you are correct, sometimes there are special cases where copying is not optimal.

But both during training and inference we never had entities with punctuation (you can simply apply a regexp for that). So consider `"Einstein, was a german scientist."` we will actually give to the model `" Einstein , was a german scientist ."`  as the source and `" [ Einstein ] , was a german scientist."` as the target.

**Comment by LittlePea13** [comment]
I see, thanks for the answer. The key is then adding a space around entities, since that more or less covers most situations. Just to be clear, I assume then that tokenisation is done after the "[]{}" are added right?

**Comment by nicola-decao** [comment]
What do you mean after? You have source and target and both have possibly different tokenizations.

**Comment by LittlePea13** [comment]
Sorry if it wasn't clear. I thought that perhaps one option would be to add the tokens to the tokenized source text to generate the target tokenized text, and that way have the same tokens on both sides (except the corresponding to []{}). But you just answered my doubt. I also imagine the model is robust to those changes, even when forcing the decoding.
