### ISSUE TITLE
'GENREHubInterface' object has no attribute '_build_batches'

### ISSUE THREAD

**Issue by vatsalkachhia** [facebookresearch/GENRE#17]
While Inferring the output for end-to-end entity linking with the "fairseq_e2e_entity_linking_aidayago" model this error message appears.

code :
from genre.fairseq_model import GENRE
from genre.entity_linking import get_end_to_end_prefix_allowed_tokens_fn_fairseq as get_prefix_allowed_tokens_fn
from genre.utils import get_entity_spans_fairseq as get_entity_spans
model = GENRE.from_pretrained("/content/GENRE/fairseq_e2e_entity_linking_aidayago").eval()

sentences = ["In 1921, Einstein received a Nobel Prize."]

prefix_allowed_tokens_fn = get_prefix_allowed_tokens_fn(model, sentences)

model.sample(
    sentences,
    prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
)

error msg -> AttributeError: 'GENREHubInterface' object has no attribute '_build_batches'
error : 
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f37ef923b5f4> in <module>()
      5 model.sample(
      6     sentences,
----> 7     prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
      8 )

2 frames
/usr/local/lib/python3.7/dist-packages/genre/fairseq_model.py in sample(self, sentences, beam, verbose, **kwargs)
     24             return self.sample([sentences], beam=beam, verbose=verbose, **kwargs)[0]
     25         tokenized_sentences = [self.encode(sentence) for sentence in sentences]
---> 26         batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
     27         return [
     28             [

/usr/local/lib/python3.7/dist-packages/genre/fairseq_model.py in generate(self, tokenized_sentences, inference_step_args, skip_invalid_size_inputs, *args, **kwargs)
     45             raise NotImplementedError("prefix generation not implemented for BART")
     46         res = []
---> 47         for batch in self._build_batches(tokenized_sentences, skip_invalid_size_inputs):
     48             src_tokens = batch["net_input"]["src_tokens"]
     49             results = super(BARTHubInterface, self).generate(

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 948             type(self).__name__, name))
    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'GENREHubInterface' object has no attribute '_build_batches'

**Comment by nicola-decao** [comment]
Did you use the PR branch of fairseq as indicated in the notebook?
