### ISSUE TITLE
Runtime error when running mgenre example

### ISSUE THREAD

**Issue by Aditi138** [facebookresearch/GENRE#22]
Hey,

I ran the commands as-is in the example_mgenre script, however I am getting the following error when running models.sample:

model.sample(
    sentences,
    prefix_allowed_tokens_fn=lambda batch_id, sent: [
        e for e in trie.get(sent.tolist()) if e < len(model.task.target_dictionary)
    ],
)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr2/home/<user>/GENRE/genre/fairseq_model.py", line 38, in sample
    batched_hypos = self.generate(
  File "/usr2/home/<user>/GENRE/genre/fairseq_model.py", line 87, in generate
    def generate(self, *args, **kwargs) -> List[List[Dict[str, torch.Tensor]]]:
  File "/usr2/home/<user>/fairseq/fairseq/hub_utils.py", line 179, in generate
    generator, self.models, batch, **inference_step_args
TypeError: inference_step() argument after ** must be a mapping, not int

This is the fairseq version I installed (https://github.com/nicola-decao/fairseq/tree/fixing_prefix_allowed_tokens_fn)

**Comment by nicola-decao** [comment]
Working on it

**Comment by nicola-decao** [comment]
@Aditi138 solved :) Thanks for reporting the bug :)

**Comment by Aditi138** [comment]
Thanks a lot!
