### ISSUE TITLE
Tagging multiple spans at a time

### ISSUE THREAD

**Issue by luigi-asprino** [facebookresearch/GENRE#28]
Hi,

Thank you for your work, really interesting!
I'm using mGENRE model (I'm following [these instructions](https://github.com/facebookresearch/GENRE/tree/main/examples_mgenre)) and it works fine.
From the examples, it seems that is possible to tag only a text span (for sentence) at a time.
I was wondering if it is possible to tag multiple spans at a time e.g. [START] Einstein [END] was a German [START] physicist [END]

Thanks!

**Comment by nicola-decao** [comment]
Hi! No, it is not possible. GENRE for Entity Disambiguation is trained as normal ED models so you need to input one mention at a time.

**Comment by luigi-asprino** [comment]
Ok, thank you!
