### ISSUE TITLE
How to train on a new set of entities?

### ISSUE THREAD

**Issue by amirj** [facebookresearch/GENRE#32]
How to train the entity linking model on a specific domain (e.g medical) with a pre-defined set of entities rather than Wikipedia?

**Comment by nicola-decao** [comment]
Hi, if you want to train on new data then you need to build your own input/ output file pairs. If you want to use `fariseq` to train then you can use https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/preprocess_fairseq.sh and https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/train.sh to preprocess and train the model (or modified version of that to accomondate your needs and number of machines you want to use etc..).

**Comment by ding00** [comment]
> Hi, if you want to train on new data then you need to build your own input/ output file pairs. If you want to use `fariseq` to train then you can use https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/preprocess_fairseq.sh and https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/train.sh to preprocess and train the model (or modified version of that to accomondate your needs and number of machines you want to use etc..).

Is it possible to change the entities set to my own set(e.g enterprises KB), but without training or finetuning the model?

**Comment by nicola-decao** [comment]
@ding00 Yes it is possible. For example, if you use https://github.com/facebookresearch/GENRE/blob/a2b949cd2ceb8c6c5efa32d27d90bd9894f598f0/genre/utils.py#L148 you need to pass `mention_trie`, `candidates_trie`, and `mention_to_candidates_dict` based on your KB.

**Comment by vnik18** [comment]
@nicola-decao If we want to do entity linking for a new set of entities without training or fine-tuning the model, would we do something similar as you mentioned above, with the `get_end_to_end_prefix_allowed_tokens_fn_hf` function? That is, would we pass it all 3 parameters `mention_trie`, `candidates_trie` and `mention_to_candidates_dict` to this function?

**Comment by nicola-decao** [comment]
These arguments are just for inference not for training. If you train with different entities then indeed you would need to provide different arguments. However, they are optional. You can pass `mention_trie` or `candidates_trie`, neither of the two or both. If you pass `mention_to_candidates_dict` you don't need the other two.
