### ISSUE TITLE
why do  the same words in different sentence have different entity linking results? 

### ISSUE THREAD

**Issue by BinLingNie** [facebookresearch/GENRE#33]
Sentence 1: "Orthostatic hypotension was ameliorated 4 days after withdrawal of selegiline and totally abolished 7 days after discontinuation of the drug ."
Entity linking results: [[0, 23, "Orthostatic_hypotension"], [67, 10, "Selegiline"], [136, 4, "Drug"]]

Sentence 2: "A lesser degree of orthostatic hypotension occurred with standing ."
Entity linking results: [[57, 8, "Standing"], [69, 0, "__A"]]

why do the words "orthostatic hypotension" in sentence 2 link with nothing?

**Comment by nicola-decao** [comment]
Because the model is not perfect 😅

What function are you using? `.sample` or `get_entity_spans`?

**Comment by BinLingNie** [comment]
> Because the model is not perfect 😅
> 
> What function are you using? `.sample` or `get_entity_spans`?

i am using get_entity_spans

**Comment by nicola-decao** [comment]
Maye try also `.sample` sometimes gives better results. Also if you are not using a `mention_trie` and. a `mention_to_candidates_dict` results are expected to be much worse of course.

**Comment by BinLingNie** [comment]
> Maye try also `.sample` sometimes gives better results. Also if you are not using a `mention_trie` and a `mention_to_candidates_dict` results are expected to be much worse of course.

thanks
