### ISSUE TITLE
List of Languages Supported?

### ISSUE THREAD

**Issue by DGaffney** [facebookresearch/GENRE#34]
Hello! I'm scanning the ArXiV paper right now for it, and can't seem to figure out if there's a canonical list of languages served by this current implementation (i.e. which languages can the model "read" in order to extract meaningful entities encoded between [START] and [END] tokens). Do you have the list of languages which can be parsed by the `mGENRE` model?

**Comment by nicola-decao** [comment]
Hi. Table 10 shows that.

**Comment by wukong86372** [comment]
where is table 10?

**Comment by nicola-decao** [comment]
At page 17

**Comment by wukong86372** [comment]
I didn’t realize that the "table 10" you said refers to the paper. my bad. sry.

**Comment by nicola-decao** [comment]
@wukong86372 no problem!
