### ISSUE TITLE
Wikiextractor version and Wikidata 

### ISSUE THREAD

**Issue by yuwfan** [facebookresearch/GENRE#35]
Hi, I have some issues when I am running `download_wiki.sh`. I noticed that the latest [wikiextractor](https://github.com/attardi/wikiextractor) doesn't have "--list --sections" option. Could you share which version you use?

Besides, could you also guide how to get this data `wikidata-all.json`?

Thank you for the response!

**Comment by nicola-decao** [comment]
I don't have access to the machine I used for those experiments anymore so I cannot tell for sure what version I used. Maybe in the new version there are similar options. Those 2 arguments basically say to wikiextractor to keep lists and to keep section titles and hierarchy.

**Comment by mrwunderbar666** [comment]
For people who are still interested in replicating this repository. It appears that the authors used this fork of wikiextractor: https://github.com/iambotHQ/wikiextractor/tree/master
