### ISSUE TITLE
mGENRE for HuggingFace

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/GENRE#43]
When the `mGENRE` model's interface for HuggingFace 🤗  will be available?
Thank you!

**Comment by nicola-decao** [comment]
Hi! The model for HuggingFace is already available. See both examples_genre and examples_mgenre.

**Comment by paulthemagno** [comment]
@nicola-decao I saw [here](https://github.com/facebookresearch/GENRE/tree/main/examples_mgenre) the examples of **mGENRE** and I found:
```python
# for pytorch/fairseq
from genre.fairseq_model import mGENRE
model = mGENRE.from_pretrained("../models/fairseq_multilingual_entity_disambiguation").eval()

# for huggingface/transformers
# from genre.hf_model import GENRE
# model = GENRE.from_pretrained("../models/hf_entity_disambiguation_aidayago").eval()
```

so I don't see the model of **HuggingFace** for **mGENRE**. How can I load it? Do I have to use this [script](https://github.com/huggingface/transformers/blob/master/src/transformers/models/bart/convert_bart_original_pytorch_checkpoint_to_pytorch.py)?

**Comment by loretoparisi** [comment]
my impression is that the [hf_model](https://github.com/facebookresearch/GENRE/blob/main/genre/hf_model.py) interface for the class `mGENRE` is missing, while the class `GENRE` is here https://github.com/facebookresearch/GENRE/blob/73f7801fe80bf6d47afaa04b1851faa9f48cbc92/genre/hf_model.py#L60

**Comment by nicola-decao** [comment]
You are correct, we haven't converted it to HuggingFace!  But you can use this script to do it https://github.com/huggingface/transformers/blob/master/src/transformers/models/bart/convert_bart_original_pytorch_checkpoint_to_pytorch.py

**Comment by loretoparisi** [comment]
@nicola-decao thank you, so just t understand: as soon as I convert the `fairseq` bart model to the `torch` model, how can I load it? using the class`GENRE` with that model? I assume that the "functions" would be the same, but the output differens, if there is not `mGENRE` wrapper around it...

Thank you in advance!

**Comment by nicola-decao** [comment]
@loretoparisi After converting it you can just load it using the `GENRE` class: there is no specific things I do in mGENRE

**Comment by loretoparisi** [comment]
@paulthemagno so we can try in that way!

**Comment by jquach12** [comment]
Hi @nicola-decao . Just wondering if I am missing something here when attempting to convert the fairseq bart model from https://dl.fbaipublicfiles.com/GENRE/fairseq_multilingual_entity_disambiguation.tar.gz to the torch model. Thanks!

`python convert_bart_original_pytorch_checkpoint_to_pytorch.py /models/fairseq_multilingual_entity_disambiguation/model.pt .`

```
Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /root/.cache/torch/hub/master.zip
100%|██████████████████████| 3715581256/3715581256 [04:43<00:00, 13124996.66B/s]
1042301B [00:00, 1236210.46B/s]
456318B [00:00, 674730.00B/s]
Traceback (most recent call last):
  File "convert_bart_to_pytorch.py", line 150, in <module>
    convert_bart_checkpoint(args.fairseq_path, args.pytorch_dump_folder_path, hf_checkpoint_name=args.hf_config)
  File "/anaconda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "convert_bart_to_pytorch.py", line 96, in convert_bart_checkpoint
    bart = load_xsum_checkpoint(checkpoint_path)
  File "convert_bart_to_pytorch.py", line 77, in load_xsum_checkpoint
    hub_interface.model.load_state_dict(sd["model"])
  File "/opt/topic_discovery/GENRE/fairseq/models/fairseq_model.py", line 117, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layer_norm.weight", "encoder.layer_norm.bias", "decoder.layer_norm.weight", "decoder.layer_norm.bias". 
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([256001, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([256001, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([256001, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
```

**Comment by jquach12** [comment]
Hi @nicola-decao . Just wondering if I am missing something here when attempting to convert the fairseq bart model from https://dl.fbaipublicfiles.com/GENRE/fairseq_multilingual_entity_disambiguation.tar.gz to the torch model e.g. a missing hf_config. Thanks!

python convert_bart_original_pytorch_checkpoint_to_pytorch.py /models/fairseq_multilingual_entity_disambiguation/model.pt .

Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /root/.cache/torch/hub/master.zip
100%|██████████████████████| 3715581256/3715581256 [04:43<00:00, 13124996.66B/s]
1042301B [00:00, 1236210.46B/s]
456318B [00:00, 674730.00B/s]
Traceback (most recent call last):
  File "convert_bart_to_pytorch.py", line 150, in <module>
    convert_bart_checkpoint(args.fairseq_path, args.pytorch_dump_folder_path, hf_checkpoint_name=args.hf_config)
  File "/anaconda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "convert_bart_to_pytorch.py", line 96, in convert_bart_checkpoint
    bart = load_xsum_checkpoint(checkpoint_path)
  File "convert_bart_to_pytorch.py", line 77, in load_xsum_checkpoint
    hub_interface.model.load_state_dict(sd["model"])
  File "/GENRE/fairseq/models/fairseq_model.py", line 117, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layer_norm.weight", "encoder.layer_norm.bias", "decoder.layer_norm.weight", "decoder.layer_norm.bias". 
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([256001, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([256001, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([256001, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).

**Comment by loretoparisi** [comment]
Any chance to provide converted weights for mGENRE?

Thanks!

> You are correct, we haven't converted it to HuggingFace!  But you can use this script to do it https://github.com/huggingface/transformers/blob/master/src/transformers/models/bart/convert_bart_original_pytorch_checkpoint_to_pytorch.py

**Comment by nicola-decao** [comment]
Sorry that it took more than a yeah ☹️ It is finally in the huggingface hub alongside all the other models:
* **https://huggingface.co/facebook/mgenre-wiki**

@loretoparisi 
@takiholadi
@paulthemagno 
@caijie12138
@code-s-x
@thomasgirault

**Please spread the news! 🚀**

**Comment by loretoparisi** [comment]
Wow that's amazing! @paulthemagno let's try it out!

**Comment by loretoparisi** [comment]
> Sorry that it took more than a year ☹️ It is finally in the huggingface hub alongside all the other models:
> 
> * **https://huggingface.co/facebook/mgenre-wiki**
> 
> 
> 
> @loretoparisi 
> 
> @takiholadi
> 
> @paulthemagno 
> 
> @caijie12138
> 
> @code-s-x
> 
> @thomasgirault
> 
> 
> 
> **Please spread the news! 🚀**

Done!

https://twitter.com/loretoparisi/status/1535319068387033088?s=21&t=TpE_Jlnb69h0yVlhH9p6Hg

**Comment by nicola-decao** [comment]
@loretoparisi hahaha thank you! I'll do a tweet next week as well 😉
