### ISSUE TITLE
how much memory does mGENRE need?

### ISSUE THREAD

**Issue by dinani65** [facebookresearch/GENRE#44]
Hello,
I have a question, what are the requirements to run mGENRE in terms of memory and cpu/gpu?
Many thanks,

**Comment by dinani65** [comment]
I appreciate it if u can answer my comment

**Comment by nicola-decao** [comment]
You do not need a GPU to run mGENRE. In terms of memory: in my machine the model occupies 2231MiB and another ~100MiB are necessary to run inference.

**Comment by appledora** [comment]
How about while inferring with the tries to obtain wikiID as well? I have tried to run inference on colab with around 12GB ram, yet it kept crashing on loading the models and provided Marisa Trie.

**Comment by dersuchendee** [comment]
Same for me
