### ISSUE TITLE
Are default arguments for create_input function missing?

### ISSUE THREAD

**Issue by kambehmw** [facebookresearch/GENRE#46]
https://github.com/facebookresearch/GENRE/tree/main/examples_genre#pre-processing

Following the steps above, I ran the preprocessing as shown in the following command and encountered an error.
```
$ python scripts_genre/convert_kilt_to_fairseq.py datasets/blink-dev-kilt.jsonl preprocessed_datasets/
INFO:root:Loading datasets/blink-dev-kilt.jsonl
Processing:   0%|                                                                                | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts_genre/convert_kilt_to_fairseq.py", line 80, in <module>
    source, target = convert_kilt_to_fairseq(
  File "scripts_genre/convert_kilt_to_fairseq.py", line 29, in convert_kilt_to_fairseq
    source.append(create_input(doc, max_length=384))
TypeError: create_input() missing 2 required positional arguments: 'start_delimiter' and 'end_delimiter'
```

https://github.com/facebookresearch/GENRE/blob/main/genre/utils.py#L45

It seems to me that the start_delimiter and end_delimiter in the create_input function are correct to have default arguments.
I would appreciate it if you could advise me if my execution procedure is wrong.

**Comment by nicola-decao** [comment]
You are right but I don't want to set the default since for mGENRE I used different delimiters. Now `convert_kilt_to_fairseq.py` is fixed.

**Comment by kambehmw** [comment]
Thank you for your quick response and for publishing such a great OSS.
