### ISSUE TITLE
Best practice to link already known entities

### ISSUE THREAD

**Issue by paulthemagno** [facebookresearch/GENRE#47]
I'm executing some examples in [this page](https://github.com/facebookresearch/GENRE/tree/main/examples_genre) with **hf_e2e_entity_linking_aidayago** model. I have already found the entities, so **I only want to link them to Wikipedia given a list of hints**. I have encountered some problems:

- When I put more than one `mention_trie` I don't see all the results, for example in this case:

```python
from genre.entity_linking import get_end_to_end_prefix_allowed_tokens_fn_hf as get_prefix_allowed_tokens_fn
from genre.utils import get_entity_spans_hf as get_entity_spans
model = GENRE.from_pretrained("../models/hf_e2e_entity_linking_aidayago").eval()

sentences = ["In 1921, Einstein received a Nobel Prize."]

get_entity_spans(
    model,
    sentences,
    mention_trie=Trie([
        model.encode(" {}".format(e))[1:].tolist()
        for e in ["Einstein", "Nobel Prize"]
    ]),
    mention_to_candidates_dict={
        "Einstein": ["Albert Einstein", "Einstein (surname)"],
        "Nobel Prize": ["Nobel Prize in Physics", "Nobel Prize in Medicine"],
    }
)
```

My output is:
```
[[(9, 8, 'Albert_Einstein')]]
```

If I remove both `Einstein` from `mention_trie` and `mention_to_candidates_dict` the result is:
```
[[(29, 11, 'Nobel_Prize_in_Physics')]]
```

But in the example shown in the README both the two entities should be visible.

- Moreover I'm encountering some problems (**maybe bug**) in the definition of the entities to search like here:

```python
sentences = ["George Walker Bush (born July 6, 1946) is an American politician and businessman who served as the 43rd president of the United States from 2001 to 2009. A member of the Republican Party, Bush previously served as the 46th governor of Texas from 1995 to 2000. He was born into the Bush family; his father, George H. W. Bush, was the 41st president of the United States from 1989 to 1993."]

get_entity_spans(
    model,
    sentences,
    mention_trie=Trie([
        model.encode(" {}".format(e))[1:].tolist()
        for e in ["George Walker Bush"]
    ]),
    mention_to_candidates_dict={
        "George Walker Bush": ["George W. Bush", "George H. W. Bush"],
    }
)
```

The result is:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-2ae034f807cd> in <module>
      1 sentences = ["George Walker Bush (born July 6, 1946) is an American politician and businessman who served as the 43rd president of the United States from 2001 to 2009. A member of the Republican Party, Bush previously served as the 46th governor of Texas from 1995 to 2000. He was born into the Bush family; his father, George H. W. Bush, was the 41st president of the United States from 1989 to 1993."]
      2 
----> 3 get_entity_spans(
      4     model,
      5     sentences,

~/genre/genre/utils.py in get_entity_spans_hf(model, input_sentences, mention_trie, candidates_trie, mention_to_candidates_dict, redirections)
    176     redirections=None,
    177 ):
--> 178     return _get_entity_spans(
    179         model,
    180         input_sentences,

~/genre/utils.py in _get_entity_spans(model, input_sentences, prefix_allowed_tokens_fn, redirections)
    141     )
    142 
--> 143     return get_entity_spans_finalize(
    144         input_sentences, output_sentences, redirections=redirections
    145     )

~/genre/utils.py in get_entity_spans_finalize(input_sentences, output_sentences, redirections)
    218                     status = "m"
    219                 else:
--> 220                     raise RuntimeError
    221 
    222             elif status == "m":

RuntimeError: 
```

- Or in case like this: #42 as said in [this comment](https://github.com/facebookresearch/GENRE/issues/42#issuecomment-880011316).

So my question is:
**if I already have the entities, but I want link them to Wikipedia (I have also candidates of the Wikipedia pages, so I only want to disambiguate them)** which is the best function ( `get_prefix_allowed_tokens_fn`, `get_entity_spans`,?) and how I have to declare my entities and my candidates to avoid these problems?

Thank you! It seems a very promising work! 😊

**Comment by nicola-decao** [comment]
The best to do disambiguation would be using the model trained for disambiguation 😅

Look at this to see how it works https://github.com/facebookresearch/GENRE/tree/main/examples_genre#example-entity-disambiguation

**Comment by paulthemagno** [comment]
Thanks @nicola-decao can you please tell me how to find more entities in a sentence? I'ven seen the example you posted and I was trying this one:
```python
sentences = ["[START_ENT]Leonardo[END_ENT] was a painter while [START_ENT]Leonardo Di Caprio[END_ENT] is an actor"]

out = model.sample(
    sentences,
    prefix_allowed_tokens_fn=lambda batch_id, sent: trie.get(sent.tolist()),
)
```

But the result is:
```
[[{'text': 'Leonardo DiCaprio', 'logprob': tensor(-0.8849)}],
 [{'text': 'Leonardo Di Cosmo', 'logprob': tensor(-2.1244)}],
 [{'text': 'Leonardo DiCaprio filmography', 'logprob': tensor(-2.2759)}],
 [{'text': 'Leonardo Di Cesare', 'logprob': tensor(-2.5289)}],
 [{'text': 'Léonardo Meindl', 'logprob': tensor(-4.0481)}]]
```

Maybe I'm doing some mistakes in the declaration of entities. And another question: is possible to add candidates as for the other models, in order to ease the disambiguation of the model? (in this case for example I should have passed `Leonardo Di Caprio` and `Leonardo Da Vinci` as possibilities. 

Thank you!

**Comment by nicola-decao** [comment]
The disambiguation model only handles one disambiguation input at a time. So you either pass "[START_ENT] Leonardo [END_ENT] was a ..." or "Leonardo was a painter while [START_ENT] Leonardo Di Caprio [END_ENT] is..".

In addition, you need to put a space between the delimiters and the mention (see my sentences above).

**Comment by paulthemagno** [comment]
ah ok so I will pass multiple sentences!

So I deduce the hints like:
```python
mention_to_candidates_dict={
        "Leonardo": ["Leonardo Di Caprio", "Leonardo Da Vinci"],
        "Leonardo Di Caprio": ["Leonardo Di Caprio", "Leonardo Da Vinci"],
    }
``` 

are not available for the disambiguation model, aren't them?

**Comment by nicola-decao** [comment]
No, the disambiguation model does not need such mapping because you are already specifying the mention.

You should do something like this:
```python
sentences = [
    "[START_ENT] Leonardo [END_ENT] was a painter while Leonardo Di Caprio is an actor",
    "Leonardo was a painter while [START_ENT] Leonardo Di Caprio [END_ENT] is an actor"
]

ties = {
    _id: Trie([
        [2] + model.encode(e)[1:].tolist()
        for e in candidates
    ])
    for _id, candidates in enumerate([
        ["Leonardo Di Caprio", "Leonardo Da Vinci"],
        ["Leonardo Di Caprio", "Leonardo Da Vinci"],
    ])
}
out = model.sample(
    sentences,
    prefix_allowed_tokens_fn=lambda batch_id, sent: tries[batch_id].get(sent.tolist()),
)
```

**Comment by paulthemagno** [comment]
Ok thank you @nicola-decao I think I'm almost there. Just some final questions for my practical use:

- Is the `[2]` you put in the Trie depending on the number of sentences I write or is it a fixed encoding to keep?
- I'm printing the results and I have the following:
```
[[{'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.0639)},
  {'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.4777)}],
 [{'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)},
  {'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.6667e+08)}],
 [{'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)},
  {'text': 'Leonardo DiCaprio', 'logprob': tensor(-0.8483)}],
 [{'text': 'Leonardo Da Vinci', 'logprob': tensor(-2.2151)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)}],
 [{'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.6667e+08)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)}]]
```
I'm seeing that every time the `sample` function returns 5 results (even if I put other sentences) so I think that if I put only two possibilities (like `Leonardo DiCaprio` and `Leonardo Da Vinci`), they will be "repeated' in the 5 results, am I right?

I also see that, in this case, these 5 possibilities are lists of 2 elements each (since I put two sentences), while if I put only 1 sentence, they are list of 1 element (seems right).  How do I have to read this values? I thought that the two sentences were "independent" (or not?).

Indeed the first element of the first result `{'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.0639)}` is **higher** than the first element of the third result: `{'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)}`, **BUT** the second element of the first result `{'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.4777)}` is **lower** of the second element of the third result:  `{'text': 'Leonardo DiCaprio', 'logprob': tensor(-0.8483)}`,

So I tried to read the first element and the second of the 5 results separately (as if they are not correlated, don't know if it's the correct thought):
```python
number_of_lables = len(out[0])
labels = {}


for choice in out:
    for i,label in enumerate(choice):
        if i not in labels:
            labels[i] = {"text": label['text'], 'logprob': label['logprob']}
        else:
            if torch.gt(label['logprob'],labels[i]['logprob']):
                labels[i] = {"text": label['text'], 'logprob': label['logprob']}
    
labels
```

obtaining:
```
{0: {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.0639)},
 1: {'text': 'Leonardo DiCaprio', 'logprob': tensor(-0.8483)}}
```

and it seemed good! Because in my first sentence I have `Leonardo Da Vinci`, while in the second one `Leonardo DiCaprio`.

But adding another row, like this:
```python
sentences = [
    "Leonardo was a painter while [START_ENT] Leonardo Di Caprio [END_ENT] is an actor",
    "[START_ENT] Leonardo [END_ENT] was a painter while Leonardo Di Caprio is an actor",
    "[START_ENT] Brown [END_ENT] was an American singer, songwriter, dancer, musician, record producer, and bandleader"
]

# generate a set of tries one for each sentence with the correct candidates
# in this case is the same for both sentences but in general is different for each
# sentence in your batch
tries = {
    _id: Trie([
        [2] + dmodel.encode(e)[1:].tolist()
        for e in candidates
    ])
    for _id, candidates in enumerate([
        ["Leonardo DiCaprio", "Leonardo Da Vinci"],
        ["Leonardo DiCaprio", "Leonardo Da Vinci"],
        ["Kwame Brown", "James Brown"],
    ])
}

out = dmodel.sample(
    sentences,
    prefix_allowed_tokens_fn=lambda batch_id, sent: tries[batch_id].get(sent.tolist()),
)
```
I have a mixed result:
```
[[{'text': 'Leonardo DiCaprio', 'logprob': tensor(-0.8483)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-2.2151)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)}],
 [{'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.6667e+08)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.0638)}],
 [{'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.4777)},
  {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)},
  {'text': 'Leonardo DiCaprio', 'logprob': tensor(-1.6667e+08)}],
 [{'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.6667e+08)},
  {'text': 'James Brown', 'logprob': tensor(-0.0789)},
  {'text': 'Kwame Brown', 'logprob': tensor(-4.0590)}],
 [{'text': 'Kwame Brown', 'logprob': tensor(-2.0000e+08)},
  {'text': 'James Brown', 'logprob': tensor(-3.3333e+08)},
  {'text': 'James Brown', 'logprob': tensor(-3.3333e+08)}]]
```

In the third element of the first results I still have `Leonardo...` while I expected to find only `James Brown` or `Kwame Brown`, indeed my script gives a wrong result:
```
{0: {'text': 'Leonardo DiCaprio', 'logprob': tensor(-0.8483)},
 1: {'text': 'James Brown', 'logprob': tensor(-1.7946)},
 2: {'text': 'Leonardo Da Vinci', 'logprob': tensor(-1.0638)}}
```

Maybe I have to use one line at time in order to avoid confusion?

Thank you in advance for the explanation, it's starting to working 😊
