### ISSUE TITLE
Details for training

### ISSUE THREAD

**Issue by antonyscerri** [facebookresearch/GENRE#5]
Hi

Having looked through the scripts and documentation its unclear if all the steps and necessary files for being able to train the various models are included. Could you let us know whether everything required has been made available or not, and if not do you plan to at some point? So far I think i've found enough to have the possibility of trying the disambiguation model training but we were more interested in the E2E models.

Thanks

Tony

**Comment by nicola-decao** [comment]
I am planning to release the code to also generate the training data in the future but I cannot give you an estimate right now. Btw, training data is just English Wikipedia where we used the provided hyperlinks and used an extra exact match heuristic to increase coverage. The training script for e2e is the same as for disambiguation.

I'll keep this issue open and as soon as I will push the code I'll write to you and close it 🙂

**Comment by antonyscerri** [comment]
Thanks for the update. I just wasnt sure of the exact format of the input and outputs the model was trained on, any particular preprocessing, sentence lengths used and chunking method etc. Will keep an eye out for it in the future.

**Comment by nicola-decao** [comment]
The model was trained from Wikipedia paragraphs (exactly as extracted from dumps) to a Markup language like this:
```
In 1921, Einstein received a Nobel Prize. -> In 1921, { Einstein } [ Albert Einstein ] received a { Nobel Prize } [ Nobel Prize in Physics ].
```
I have not used chunking/ truncation. However, when paragraphs are too long (e.g. for BART the max is 1024 BPEs) `fairseq` automatically discards these datapoints.

**Comment by vnik18** [comment]
I would like to train an end-to-end entity linking model using my own data and entities (non-Wikipedia entities). Is there a script I can use to generate training data for this?

**Comment by nicola-decao** [comment]
@antonyscerri @vnik18 I released the training dataset. Unfortunately, I do not have the code to convert a Wikipedia dump in the desired format anymore but it should not take you a lot of time to code it (since it just requires converting HTML into markdown and some regexp to clean it/ argument it). 3dcca28
