### ISSUE TITLE
get markdown for disambiguation model

### ISSUE THREAD

**Issue by paulthemagno** [facebookresearch/GENRE#50]
Is there a way to add markdown on **Wikipedia pages** to the entities using the **disambiguation model**?

Because the example in the README with `fairseq_entity_disambiguation_aidayago` or `hf_entity_disambiguation_aidayago` is this:

```python
sentences = ["Einstein was a [START_ENT] German [END_ENT] physicist."]

model.sample(
    sentences,
    prefix_allowed_tokens_fn=lambda batch_id, sent: trie.get(sent.tolist()),
)
```

While I see by using `fairseq_e2e_entity_linking_aidayago` or `hf_e2e_entity_linking_aidayago`, there is the function `get_markdown` which needs `entity_spans`.

```python
from genre.utils import get_markdown
from IPython.display import Markdown

entity_spans = get_entity_spans(
    model,
    sentences,
    mention_trie=Trie([
        model.encode(" {}".format(e))[1:].tolist()
        for e in ["Einstein", "Nobel Prize"]
    ]),
    mention_to_candidates_dict={
        "Einstein": ["Albert Einstein", "Einstein (surname)"],
        "Nobel Prize": ["Nobel Prize in Physics", "Nobel Prize in Medicine"],
    }
)

Markdown(get_markdown(sentences, entity_spans)[0])
```

In 1921, [Einstein](https://en.wikipedia.org/wiki/Albert_Einstein) received a [Nobel Prize](https://en.wikipedia.org/wiki/Nobel_Prize_in_Physics).

How can I do the same with **disambiguation model**? I tried to re-build the trie, but it didn't work for me.

**Comment by nicola-decao** [comment]
Hello, if you want to use the disambiguation models for creating markdown you first need to run a mention detection step to identify the mentions. Then you would run the entity disambiguation model on those. Eventually, you would need to create a `entity_spans` object yourself using the entities' offsets and the output of the disambiguation model.

**Comment by paulthemagno** [comment]
thanks @nicola-decao, can you please write here an example to do this?
