### ISSUE TITLE
How to threshold by probability (end-to-end model)?

### ISSUE THREAD

**Issue by mnskim** [facebookresearch/GENRE#52]
Hello, 
First of all, thank you for a fantastic code release!

I'm wondering how to threshold the results of end-to-end genre model - In the disambiguation model, since probability is given for the single entity being disambiguated, I'm able to get a good filtering with a single value of confidence, i.e 75% probability (by exponentiating the logprob),

But in the case of the end-to-end model I'm not sure how we should filter by confidence. Would it be sufficient to normalize by the number of entities found? Thanks!

**Comment by nicola-decao** [comment]
Hello, I'm not sure what you want to do. The probability of the output is of the whole sequence (i.e. both mention detection and entity disambiguation).

**Comment by mnskim** [comment]
Ah I see, I was hoping to threshold the entity disambiguation probability by some value like 75%, so that I can keep only the disambiguation results that the model is confident about - would this be possible?

**Comment by nicola-decao** [comment]
Yes it is possible but it is up to you to define the rules for thresholding.
