### ISSUE TITLE
Finetuning mGENRE using fairseq-train  -  please ensure architectures match

### ISSUE THREAD

**Issue by Valdegg** [facebookresearch/GENRE#53]
I processed my Icelandic dataset into KILT and then into fairseq binary format using the codes in the repo (with sentencepiece and mGENRE's dictionary) with the goal of finetuning mGENRE.

The model I'm using is model.pt from fairseq_multilingual_entity_disambiguation.
I used  scripts_genre/train.sh  and when I ran it I got the following error:

RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layer_norm.weight", "encoder.layer_norm.bias", "decoder.layer_norm.weight", "decoder.layer_norm.bias". 

_Exception: Cannot load model parameters from checkpoint mgenre/model.pt; please ensure that the architectures match._

I'm able to train GENRE using the same train.sh script  (for data I processed using BPE) without a problem. But not mGENRE.

I tried changing the --arch parameter to mbart_large, but still get the same error.

Any idea what parameters I need to change to make calling fairseq-train work?

**Comment by Valdegg** [comment]
https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/train.sh

**Comment by Valdegg** [comment]
I read that Fairseq first creates an initial model of the architecture indicated with --arch and, after that, it copies the parameters from the loaded model into the initial model; if there is some architectural difference, the model won't be loaded. 

So there seems to be a discrepancy in the architecture of mbart_large and mgenre, which needs to be specified in when fairseq-train is called.

Any idea what that is?

**Comment by Valdegg** [comment]
I loaded the statedict of mbart_large and compared it with the statedict of the fairseq_multilingual_entity_disambiguation model.

They both actually contain the same keys, such as "encoder.layer_norm.weight". Mysterious.

**Comment by nicola-decao** [comment]
@Valdegg what happens if you use the `--arch bart_large`?

**Comment by nicola-decao** [comment]
@Valdegg can you try to remove `--layernorm_embedding`?

**Comment by Valdegg** [comment]
@nicola-decao  I tried that but unfortunately still get the same error.

Here's the training script that I'm using:


```
### path to sentencepiece binarised fairseq dataset:
DATASET=$1
### name of the model being trained:
NAME=$2

fairseq-train $DATASET/bin/ \
    --save-dir models/$NAME \
    --tensorboard-logdir tensorboard_logs/$NAME \
    --restore-file model/mgenre/model.pt \
    --arch mbart_large  \
    --task translation  \
    --criterion label_smoothed_cross_entropy  \
    --source-lang source  \
    --target-lang target  \
    --truncate-source  \
    --label-smoothing 0.1  \
    --max-tokens 1024  \
    --update-freq 1  \
    --max-update 200000  \
    --required-batch-size-multiple 1  \
    --dropout 0.1  \
    --attention-dropout 0.1  \
    --relu-dropout 0.0  \
    --weight-decay 0.01  \
    --optimizer adam  \
    --adam-betas "(0.9, 0.999)"  \
    --adam-eps 1e-08  \
    --clip-norm 0.1  \
    --lr-scheduler polynomial_decay  \
    --lr 3e-05  \
    --total-num-update 200000  \
    --warmup-updates 500  \
    --ddp-backend no_c10d  \
    --num-workers 20  \
    --reset-meters  \
    --reset-optimizer \
    --share-all-embeddings \
    --share-decoder-input-output-embed  \
    --skip-invalid-size-inputs-valid-test  \
    --log-format json  \
    --log-interval 10  \
    --patience 200
```


And here is the error message that comes when I run it:

2```
021-08-13 10:42:37 | INFO | fairseq.trainer | Preparing to load checkpoint model/mgenre/model.pt
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/fairseq/fairseq/trainer.py", line 356, in load_checkpoint
    state["model"], strict=True, model_cfg=self.cfg.model
  File "/home/ec2-user/SageMaker/fairseq/fairseq/models/fairseq_model.py", line 117, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/torch-1.9.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layer_norm.weight", "encoder.layer_norm.bias", "decoder.layer_norm.weight", "decoder.layer_norm.bias". 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/ec2-user/SageMaker/fairseq/fairseq_cli/train.py", line 470, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/ec2-user/SageMaker/fairseq/fairseq/distributed/utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "/home/ec2-user/SageMaker/fairseq/fairseq_cli/train.py", line 137, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/home/ec2-user/SageMaker/fairseq/fairseq/checkpoint_utils.py", line 209, in load_checkpoint
    reset_meters=reset_meters,
  File "/home/ec2-user/SageMaker/fairseq/fairseq/trainer.py", line 365, in load_checkpoint
    "please ensure that the architectures match.".format(filename)
Exception: Cannot load model parameters from checkpoint model/mgenre/model.pt; please ensure that the architectures match.
```

**Comment by Valdegg** [comment]
The only keys that are in statedict of mBART but not in mGENRE are:

- final_logits_bias
- lm_head.weight
- shared.weight

The keys in mGENRE not in mBART are:

- decoder.output_projection.weight
- decoder.version
- encoder.version

This is for mbart-large-50, since mbart.cc100 isn't available.

Any idea what the architectural difference (in terms of training parameters) might be between mGENRE (i.e. mbart.cc100) and the architecture in mbart_large in fairseq?


The only way I've found to get training runing is to change the source code in fairseq/trainer.py to allow the state_dicts to not match completely.

Change the parameter strict to False in

` load_checkpoint(    state["model"], strict=True, model_cfg=self.cfg.model )`

but then some parameters from mGENRE might be skipped and the outcome might be bad...

I'll tag the other contributor, @fabiopetroni - any ideas? 
(I watched your talk on What do Machines Know a while back, was inspiring)

**Comment by nicola-decao** [comment]
ok, I have other ideas: can you please try adding `--encoder-normalize-before --decoder-normalize-before` (while keeping `--layernorm_embedding`)?

**Comment by Valdegg** [comment]
Hurray!

Training works and the first results look fine.

Thanks for the help. 

I'll let you know if finetuning mgenre on my specific-language dataset turns out to be fruitful.

**Comment by nicola-decao** [comment]
@Valdegg that's great! I'll add a note to the `.sh` then.

**Comment by Valdegg** [comment]
I fine-tuned it on my small dataset but the results were really bad, it just ruined the model. 

I think it was due to "catastrophic forgetting" where the model lost vital parameters during the fine-tuning process.

If that is the case, then some continual learning approach to fine-tuning might help.
