### ISSUE TITLE
GENRE uses more memory that mGENRE

### ISSUE THREAD

**Issue by paulthemagno** [facebookresearch/GENRE#62]
I'm doing some tests on memory occupation of **GENRE** and **mGENRE** in **GPU** models with their tries. Looking from the examples I've seen that to load **GENRE** I have to do:

```python
import pickle
from genre.trie import Trie
from genre.fairseq_model import GENRE

# load the prefix tree (trie)
with open("../data/kilt_titles_trie_dict.pkl", "rb") as f:
    trie = Trie.load_from_dict(pickle.load(f))
# for pytorch/fairseq
model = GENRE.from_pretrained("../models/fairseq_entity_disambiguation_aidayago").eval()
```

while for **mGENRE**:
```python
import pickle
from genre.trie import Trie, MarisaTrie
from genre.fairseq_model import mGENRE

with open("../data/titles_lang_all105_marisa_trie_with_redirect.pkl", "rb") as f:
    trie = pickle.load(f)
# for pytorch/fairseq
model = mGENRE.from_pretrained("../models/fairseq_multilingual_entity_disambiguation").eval()
```
Then I moved both the models to GPU doing:
```python
model.cuda()
```

I see that for **mGENRE** I have about 

- 3.5 GB of RAM allocated in CPU 
- the same in GPU.

For **GENRE** instead, I have allocated:

- 3 GB in GPU
- **8.5 in CPU**.

I think that the tries (which can't be allocated in GPU) is the resource that uses more memory, but I don't understand why with mGENRE is so lower. A thing I see is that the loading of the trie for GENRE is done with the class `Trie`, while for mGENRE with a simple pickle.

**Comment by nicola-decao** [comment]
In https://github.com/facebookresearch/GENRE/tree/main/examples_mgenre I explain that there are two ways to load a mGENRE trie:
```python
# fast but memory inefficient prefix tree (trie) -- it is implemented with nested python `dict`
# NOTE: loading this map may take up to 10 minutes and occupy a lot of RAM!
# with open("../data/titles_lang_all105_trie_with_redirect.pkl", "rb") as f:
#     trie = Trie.load_from_dict(pickle.load(f))

# memory efficient but slower prefix tree (trie) -- it is implemented with `marisa_trie`
with open("../data/titles_lang_all105_marisa_trie_with_redirect.pkl", "rb") as f:
    trie = pickle.load(f)
```
the marisa trie is memroy efficient but slower. I only implemented that for mGENRE since its original trie is extremely big.
