### ISSUE TITLE
GENRE + fairseq break in colab

### ISSUE THREAD

**Issue by senisioi** [facebookresearch/GENRE#66]
I've been trying to follow the setup described in the [examples](https://github.com/facebookresearch/GENRE/tree/main/examples_mgenre) and to run a prediction example in colab.

Apparently, there are some issues installing the current branch in colab, [here is a link to my notebook](https://colab.research.google.com/drive/1xOn8iP1-W7_WcGiRxhKe_6OhEliTS4Hw?usp=sharing).
Steps I tried:

1. Installing fairseq branch and running `from fairseq import search` gives a `ModuleNotFoundError: No module named 'examples.simultaneous_translation'`
2. I added the fairseq directory (with the `examples` dir) to the pythonpath and tried again
3. The `setup_registry` method returns `None` because the REGISTRY already exists. This breaks some call in `fairseq/criterions/__init__.py`

```
/usr/local/lib/python3.7/dist-packages/fairseq/criterions/__init__.py in <module>()
     22     CRITERION_DATACLASS_REGISTRY,
     23 ) = registry.setup_registry(
---> 24     "--criterion", base_class=FairseqCriterion, default="cross_entropy"
     25 )
     26 

TypeError: cannot unpack non-iterable NoneType object
```

**Comment by nicola-decao** [comment]
Also the problem seems happening in `from fairseq import search` not in GENRE

**Comment by dersuchendee** [comment]
It still doesn't work for me actually! See colab [here](https://colab.research.google.com/drive/1NnB5ipmGWcCC0IFcRQeCSKb5A-4tcDsV?usp=sharing)

**Comment by senisioi** [comment]
The first line should be `! rm -rf /usr/local/lib/python3.10/dist-packages/examples` to remove the pre-installed examples package.

**Comment by dersuchendee** [comment]
Thank you, but when adding pickles of wd and marisa_trie to try to get ids, it always runs out of RAM (even with colab Pro), how is that possible? Am I doing something wrong?

**Comment by senisioi** [comment]
> Thank you, but when adding pickles of wd and marisa_trie to try to get ids, it always runs out of RAM (even with colab Pro), how is that possible? Am I doing something wrong?

Indeed, it's simply too large and unfortunately the whole thing is resource-prohibitive. I ended up renting a machine on vast.ai for a day
