### ISSUE TITLE
I downloaded the model and everything related but getting request error from https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json

### ISSUE THREAD

**Issue by KemalDrop** [facebookresearch/GENRE#67]
I have all the files locally including the encoder but from time to time I get requests error from https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json website which indicates the from_pretrained function tries to download that file even if I had it. Everytime I load this happens - What do I need to do instead?

I load the disambiguation model with:
```
from genre.fairseq_model import GENRE
GENRE.from_pretrained(local_path)
```

**Comment by nicola-decao** [comment]
It seems a problem with `fairseq` rather than GENRE
