### ISSUE TITLE
hyperlinks won't open

### ISSUE THREAD

**Issue by Hparvaresh** [facebookresearch/GENRE#71]
Hello Dears,
this hyper links dont work:
[titles_lang_all105_trie_with_redirect.pkl](http://dl.fbaipublicfiles.com/GENRE/titles_lang_all105_trie_with_redirect.pkl)
[titles_lang_all105_marisa_trie_with_redirect.pkl](http://dl.fbaipublicfiles.com/GENRE/titles_lang_all105_marisa_trie_with_redirect.pkl)
please check them.
Thanks,
Parvaresh

**Comment by nicola-decao** [comment]
Checked and they work for me.
