### ISSUE TITLE
A bug on mGENRE.from_pretrained

### ISSUE THREAD

**Issue by xu1998hz** [facebookresearch/GENRE#77]
model = mGENRE.from_pretrained("fairseq_multilingual_entity_disambiguation").eval()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/home/wendaxu/GENRE/genre/fairseq_model.py", line 146, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/local/home/wendaxu/anaconda3/envs/genre/lib/python3.8/site-packages/fairseq/hub_utils.py", line 70, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/local/home/wendaxu/anaconda3/envs/genre/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/local/home/wendaxu/anaconda3/envs/genre/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 231, in load_checkpoint_to_cpu
    setattr(args, arg_name, arg_val)
AttributeError: 'NoneType' object has no attribute 'bpe'

**Comment by nicola-decao** [comment]
Are you using my version of `fairseq` ?

**Comment by xu1998hz** [comment]
Thank you for your quick response! I updated fairseq version and problem solved. A followup question, is mGENRE supports multi-gpu inference?

**Comment by nicola-decao** [comment]
No I do not think it does out of the box.

**Comment by xu1998hz** [comment]
Sorry, just to confirm, currently mGENRE is only CPU optimized at inference time? Because I was trying to load model into GPU but the inference time is still quite long.

**Comment by xu1998hz** [comment]
Sorry to keep bothering you on this thread. I really appreciated your helps in the previous responses. I still think that I haven't fully explored GPU at inference time. Currently, I just sent mGENRE model to GPU by 

model = mGENRE.from_pretrained("fairseq_multilingual_entity_disambiguation").eval()
model = model.to(device)

I didn't provide further modifications into any other codes. My speed is around 16000 per 5 hours with batch size 1000. Do I have to modify any other part of the codes in order to activate GPU inference? An example for GPU inference will be really appreciated! Thank you in advance.

**Comment by xu1998hz** [comment]
Also this is in the entity linking pipeline

**Comment by nicola-decao** [comment]
`model.to(device)` is correct but I think you are using a batch size that is too high. If you are using constrained beam search you definitely have a bottleneck there since it is not implemented in parallel across batches.

**Comment by xu1998hz** [comment]
Oh I see. What is the optimal batch size that you used?

**Comment by nicola-decao** [comment]
Something like 4-8
