### ISSUE TITLE
Question: mGENRE entity-linking model

### ISSUE THREAD

**Issue by JulesBelveze** [facebookresearch/GENRE#78]
Hey peeps, first of all, thanks for the awesome work. 😃 

I am getting familiar with both GENRE & mGENRE by going through the papers and following the examples you shared.
I'm willing to perform *End-to-End Entity Linking* with mGENRE but I can't seem to find the fine-tuned models..

Are you planning on releasing the model's checkpoints? Or is there any way I can use the `fairseq_multilingual_entity_disambiguation` checkpoints to perform entity linking as in the [GENRE example](https://github.com/facebookresearch/GENRE/blob/main/examples_genre/examples.ipynb)?

Thanks for your help!

**Comment by nicola-decao** [comment]
We haven't trained mGENRE for the e2e task sorry ☹️ so there is no plan to release that model

**Comment by JulesBelveze** [comment]
Alright, thanks for the fast answer @nicola-decao.
Would it be alright to perform multiple entity disambiguation at once? By e.g. creating a sentence of the following format:
```
"With the [START] Green Line [END] just outside, this unit is perfect for the downtown commuter or [START] Boston College [END] grad student.
```

**Comment by nicola-decao** [comment]
What do you mean alright? The model has not been trained for that

**Comment by JulesBelveze** [comment]
If this would be correct from a modeling point of view. As you guys might have trained the model on performing multiple disambiguations at once. 
But thanks for pointing out that you have not 😺
