### ISSUE TITLE
Crash while using mention table

### ISSUE THREAD

**Issue by xu1998hz** [facebookresearch/GENRE#79]
I used "mention2wikidataID_with_titles_label_alias_redirect.pkl" and "wikidataID2lang_title-normalized_with_redirect.pkl" to add constraints on the search space. However, I received the following errors on one example.

The example was "LONDON, England (CNN) -- There are some circuits that are cornerstones of the Formula 1 calendar: the Monacos and  [START] Silverstones [END]  whose every twist and turn are known intimately by the drivers and engineers."

File ~/GENRE/fairseq/fairseq/sequence_generator.py:902, in <listcomp>(.0)
    899 else:
    900     print(finalized)
    901     attn = [
--> 902         finalized[i // beam_size][i % beam_size]["attention"].transpose(1, 0)
    903         for i in range(bsz * beam_size)
    904     ]
    906 if src_tokens.device != "cpu":
    907     src_tokens = src_tokens.to("cpu")

IndexError: list index out of range

**Comment by nicola-decao** [comment]
Did you use my version of `fariseq`?

**Comment by xu1998hz** [comment]
I just printed myself to figure out some potential bugs

**Comment by xu1998hz** [comment]
Yes, version is correct. The code works OK without using mention table

**Comment by nicola-decao** [comment]
Show me the code you are running
