### ISSUE TITLE
Transformers inference requires fairseq

### ISSUE THREAD

**Issue by daltonj** [facebookresearch/GENRE#8]
According to the documentation the transformers inference should not require fairseq. However, it appears that current version has a dependence on it when loading the title trie (and importing it has a possible version / environment issues).

Code to reproduce available on colab:
https://colab.research.google.com/drive/1Yo7pn-JhCaxGDs0lcGpbdpsgnd5qRY9z?usp=sharing

Error is below.

Executing:
import pickle
with open("/content/kilt_titles_trie.pkl", "rb") as f:
    trie = pickle.load(f)
def prefix_allowed_tokens_fn(batch_id, sent):
    return trie.get(sent.tolist())

Results in:
ImportError                               Traceback (most recent call last)
<ipython-input-8-09936998f537> in <module>()
      7 
      8 with open("/content/kilt_titles_trie.pkl", "rb") as f:
----> 9     trie = pickle.load(f)
     10 
     11 def prefix_allowed_tokens_fn(batch_id, sent):

1 frames
/content/GENRE/genre/base_model.py in <module>()
     10 
     11 import torch
---> 12 from fairseq import search, utils
     13 from fairseq.models.bart import BARTHubInterface, BARTModel
     14 from omegaconf import open_dict

ImportError: cannot import name 'search' 

Google colab
Python 3.7.9

Note: This follows up on the issue: https://github.com/facebookresearch/GENRE/issues/6 that finds an incompatibility issue with versions for python 3.6.9. 

I suspect there are also related colab environment issues with fairseq library versions as various install methods don't seem to resolve the issue.  Any ideas?

**Comment by nicola-decao** [comment]
Thanks for reporting this! I will take a look.

**Comment by nicola-decao** [comment]
Fixed! :)
