### ISSUE TITLE
Question: 'fairseq_multilingual_entity_disambiguation' on HuggingFace hub?

### ISSUE THREAD

**Issue by JulesBelveze** [facebookresearch/GENRE#80]
Hi all,

I saw that you have a bunch of models pushed on the HuggingFace hub and in the repo you mention that mGENRE will be available on transformers soon. Do you have any idea when you will release your fairseq_multilingual_entity_disambiguation to the hub? 😺

Thanks for your precious help,
Cheers!

**Comment by nicola-decao** [comment]
Hi! I am planning to do it today or tomorrow :D I'll ping you when I'm done

**Comment by nicola-decao** [comment]
@JulesBelveze @ConstantinSchmidts
Done 😊
https://huggingface.co/facebook/mgenre-wiki
