### ISSUE TITLE
alignment between candidate and KILT wikipedia data source

### ISSUE THREAD

**Issue by cnut1648** [facebookresearch/GENRE#85]
Hello,
I'm working on the Entity Disambiguation task.
According to the [documentation](https://github.com/facebookresearch/GENRE/blob/main/examples_genre/examples.ipynb), GENRE Trie seems to be made from [BLINK's Wikipedia dump](http://dl.fbaipublicfiles.com/BLINK/enwiki-pages-articles.xml.bz2) which is what [KILT](https://github.com/facebookresearch/KILT) uses.
I also think GENRE is using [KILT formatted data](https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/download_all_datasets.sh), meaning that candidates & entities in those datasets follow KILT data source entities. Is that correct?
I found that sometimes candidates given by GENRE (eg "German Brazilian") do not appear in KILT data source. I wonder if there exists a mapping between GENRE outcome to KILT data source entities. This will be helpful for us to build a page that links to the actual wikipedia id (since KILT has it). 
Thanks!

**Comment by nicola-decao** [comment]
Can you give me an example of code where this happens?

The intention is that GENRE always outputs a valid page name from KILT. The constrained beam search should make that happen.

**Comment by cnut1648** [comment]
Hi @nicola-decao, for example, consider the first line of `aida-train-kilt.jsonl` (downloaded from [your script](https://github.com/facebookresearch/GENRE/blob/main/scripts_genre/download_all_datasets.sh)), some of the candidates are "Ethnic Germans," "Canadians of German ethnicity," "German American."

If you search these three candidates in KILT (`kilt_knowledgesource.json` downloaded from [official KILT repo](https://github.com/facebookresearch/KILT#kilt-knowledge-source)) I don't think there is any entry with `wikipedia_title` equal to "Ethnic Germans" or "Canadians of German ethnicity" or "German American." (I think they should instead be "German ethnic," "German Canadians," and "German Americans.")

There are also instances whose labels are not in the KILT, for example `aida-train-kilt.jsonl` line 147 ('Channel 2 (Israel)')

Please let me know if I misunderstand anything. Thanks!

**Comment by nicola-decao** [comment]
OK make sense now! AIDA uses YAGO as a knowledge base so there is no alignment with Wikipedia. `aida-train-kilt.jsonl` contains standard candidates that most researchers are using to evaluate EL models.

**Comment by cnut1648** [comment]
Oh I see, from the name I mistakenly thought candidates from `aida-train-kilt.jsonl`'s candidates align with KILT. Thanks for the clarification.
