### ISSUE TITLE
Question: Running genre on multiple GPUs

### ISSUE THREAD

**Issue by vmedaert** [facebookresearch/GENRE#86]
Is there a way to run the model on multiple GPUs? Wrapping the model in torch.nn.DataParallel doesn't seem to make any difference.
Thank you for your time

**Comment by nicola-decao** [comment]
I trained the model on multiple GPUs using `fairseq`. For inference, I did not bother to implement it on multiple GPUs but it is possible for sure. However, I am not an expert on this so I do not know how to help.
