### ISSUE TITLE
format of entries for entity linking training

### ISSUE THREAD

**Issue by Denescor** [facebookresearch/GENRE#88]
Hello,

I'm trying to learn GENRE on my own datasets for the Entity Linking task.
However, I didn't find on your script the format of the data (KILT and fairseq entries) for this task (there's only the scripts for the ED task).
Without the exact format, I couldn't be sure that GENRE learn correctly the task. 

Is it possible to share the format of your data for the EL task ? 
Or explain the difference between the format for training on EL task and training on ED task ?

Thanks for your responses.

**Comment by nicola-decao** [comment]
The training of the EL task is done via a sequence-to-sequence objective. The input text is plain text and the output is a markup language like this example:
```
Input: In 1921, Einstein received a Nobel Prize.
Output: In 1921, { Einstein } [ Albert Einstein ] received a { Nobel Prize } [ Nobel Prize in Physics ] .
```

**Comment by Denescor** [comment]
Hello

Thanks for your response but my question was more about the construction of a dataset to train GENRE.

In your ED model, there is only 1 mention by entry, which is unusual for EL task (where the entry is 1 plain document) and ED task (because the context between the differents mentions of a document is lost). 
I don't know if this choice is a constraint for fairseq or an optimisation of the model's objective.

I would like to know if for the EL task, I have to process 1 mention by entry or if I have to process 1 document by entry.
