### ISSUE TITLE
Quesitons about the Generation of " [" and " ]".

### ISSUE THREAD

**Issue by alkaideemo** [facebookresearch/GENRE#9]
In the evaluation mode, I was confused about how the model generate token " [" and " ]". I have read the code in the `entity_linking.py` file, in the funcation `_get_end_to_end_prefix_allowed_tokens_fn()`, I didn't see any code related to the generation of " [" or " ]".

In addition to this,  function `get_trie_entity` in the `entity_linking.py` return the candidates tokens constrained by the entities trie.
https://github.com/facebookresearch/GENRE/blob/1e7807c34cd656cd0b05be0df035902415ab9e40/genre/entity_linking.py#L221
In this line, sent[pointer_end:] will point to a sequence start with token id 35524, which is ' }'. So use the trie loaded from kilt_titles_trie.pkl will alwalys get [] as return, beacase kilt_titles_trie.pkl is start with token id 2 (`</s>`).

I'm not sure if this is the right understanding, look forward to your reply.

**Comment by nicola-decao** [comment]
The KILT trie was constricted for entity disambiguation. For end-to-end entity linking you need to build your own trie with `} [ ENTITY ]` for each entity.

**Comment by vnik18** [comment]
@nicola-decao Is it possible for you to share the code that I can use to build my own trie, that I can use for entity linking? I want to do entity linking on non-Wikipedia entities.

**Comment by vnik18** [comment]
@nicola-decao Thank you for the prompt reply! I just have two additional questions:

1. in the following snippet:  `trie = Trie([[2] + model.encode(entity)[1:].tolist() for entity in entities])`, what does `[2]` stand for?
2. It looks like the code snippet you mentioned will be given as input to the `prefix_allowed_tokens_fn`, for example like this:
```
prefix_allowed_tokens_fn = get_prefix_allowed_tokens_fn(
    model,
    sentences,
    mention_trie=Trie([[2] + model.encode(entity)[1:].tolist() for entity in entities])
)
```
If yes, then won't this just be adding the constraint that only the entities in the `entities` list need to be linked to a Wikipedia entity?

I am interesting in building a "brand new" trie that only contains non-Wikipedia entities, from my entity linking corpus. Please let me know if there is any code available for this?

Thank you very much!

**Comment by nicola-decao** [comment]
1. `2` is the BOS token,
2. Yes.

If you use a `candidates_trie` the model can only generate the entities that are in the trie passed.
