### ISSUE TITLE
Why do you prepend `eos_token_id' to sent_orig

### ISSUE THREAD

**Issue by WenzhengZhang** [facebookresearch/GENRE#92]
Hi, I'm confused about this [line](https://github.com/facebookresearch/GENRE/blob/08af8d0119ed60692e428791be98a17db73996b7/genre/entity_linking.py#L131). Why do you prepend `eos_token_id` to each sent_orig instead of `bos_token_id`?

**Comment by nicola-decao** [comment]
Mmm, probably that is a bug. In all experiments `eos_token_id = bos_token_id` so it did not make a difference. Have you tried changing it?

**Comment by WenzhengZhang** [comment]
Thanks for your reply! I tried changing it and found it didn't make a difference. I found you seemed to set `2` as both `eos_token_id` and `bos_token_id`.
